### ISSUE TITLE
apa7 package compatibiliy

### ISSUE THREAD

**Issue by yuvso** [avi-kluger/apa7#1]

**Comment by yuvso** [comment]
Hi Avi, I used apa7 on a previous version of R. When upgrading to R 4.2.2, apa7 would not load.

Warning in install.packages :
  package ‘apa7’ is not available for this version of R

**Comment by avi-kluger** [comment]
Hi,

Thank you for letting me know. I tested it on R 4.2.2 and found no errors. I re-installed it with 

library(devtools)
install_github("avi-kluger/apa7", force = TRUE)

library(apa7)
help("apa7corr")

It complained about older version of RTOOLS. I downloaded the new version at https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html

Then I have upgraded all the packages that install_github complained about being older version. I reran the above code and tested it, and it ran successfully. 

Could you let me know if the above steps solve your issue?

Avi

**Comment by yuvso** [comment]
> library(devtools) install_github("avi-kluger/apa7", force = TRUE)
> 
> library(apa7) help("apa7corr")

I've run your solution - It now works!  thanks so much! 

Yuval
